Repository kijongjo/Nanum-project, pull requests merged in 2020-04, with the labels that each got.

#196 기능 : ClassIn 페이지 컨텐츠 금액표시 추가 및 수정
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookEndD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookRefundD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/mypageIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherDiscription.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/wishlist/wishlistClass.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/wishlist/wishlistSpace.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/wishlist/wishlistTeacher.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
  openkitchen/src/main/webapp/resources/css/lay03_sideBar.css
Labels: 뷰, 페이지

#197 기능 : teacherIn 페이지 css 수정
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
  openkitchen/src/main/webapp/resources/css/contents.css
  openkitchen/src/main/webapp/resources/css/reset.css
Labels: 뷰, 페이지

#198 기능 : spaceIn 페이지 css 수정
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
  openkitchen/src/main/webapp/resources/css/contents.css
Labels: 뷰, 페이지

#199 기능 : footer 현재 생성된 페이지와 결합, banner 위치 수정
  openkitchen/src/main/webapp/WEB-INF/views/admin/memberAdmin.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perSpaceD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perSpaceD2.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perTeacherD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perTeacherD2.jsp
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/footer.jsp
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/openClassD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/openSpaceD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/myInfo/alarmD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/myInfo/message.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/mypageIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherDiscription.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/wishlist/wishlistIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
  openkitchen/src/main/webapp/resources/css/contents.css
  openkitchen/src/main/webapp/resources/css/lay03_sideBar.css
  openkitchen/src/main/webapp/resources/img/icon/instagram.png
Labels: 뷰, 페이지

#200 classIn, teacherIn, spaceIn 페이지 메인 슬라이드 기능 구현
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/footer.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
  openkitchen/src/main/webapp/resources/css/contents.css
  openkitchen/src/main/webapp/resources/css/index-slide.css
Labels: 뷰, 비즈니스로직, 페이지

#202 기능: ajax로 더보기 기능 구현
  openkitchen/pom.xml
  openkitchen/src/main/java/kr/co/openkitchen/controller/CommonController.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/dtoTest.java
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/resources/css/index.css
Labels: 뷰, 비즈니스로직, 페이지

#203 기능: ajax 이용한 더보기 기능
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherIn.jsp
Labels: 뷰, 비즈니스로직, 페이지

#205 기타: class space teacher img 파일
  openkitchen/src/main/webapp/resources/img/classimg/c21-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c21-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c21-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c21-ds-04.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c22-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c22-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c22-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c23-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c23-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c23-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c23-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c24-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c24-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c24-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c24-ds-04.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c24-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c25-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c25-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c25-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c25-ds-04.jpg
  openkitchen/src/main/webapp/resources/img/classimg/c25-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/s21-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/classimg/s21-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/classimg/s21-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/classimg/s21-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/icon/wishlistIcon.png
  openkitchen/src/main/webapp/resources/img/profileimg/21pro.jpg
  openkitchen/src/main/webapp/resources/img/profileimg/22pro.jpg
  openkitchen/src/main/webapp/resources/img/profileimg/23pro.jpg
  openkitchen/src/main/webapp/resources/img/profileimg/24pro.jpg
  openkitchen/src/main/webapp/resources/img/profileimg/25pro.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s22-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s22-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s23-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s23-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s24-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s24-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s24-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s25-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s25-ds-02.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s25-ds-03.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s25-ds-04.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s25-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t21-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t21-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t22-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t22-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t23-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t23-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t24-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t24-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t25-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t25-ms-01.jpg
Labels: 페이지

#207 기능 : mybatis + db 연동 완료
  openkitchen/src/main/java/kr/co/openkitchen/controller/MainController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/Dao.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/OracleDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/ClassDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/Service.java
  openkitchen/src/main/java/kr/co/openkitchen/service/ServiceImple.java
  openkitchen/src/main/java/kr/co/openkitchen/service/ServiceInter.java
  openkitchen/src/main/webapp/WEB-INF/Mapper.xml
  openkitchen/src/main/webapp/WEB-INF/spring/appServlet/spring-ctx.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/test.jsp
  openkitchen/src/main/webapp/resources/img/profileimg/5pro.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t5-ms-01.jpg
Labels: 환경설정

#209 기능:scrollMoving시 움직이는 div
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherD.jsp
  openkitchen/src/main/webapp/resources/css/Header.css
  openkitchen/src/main/webapp/resources/css/classD.css
  openkitchen/src/main/webapp/resources/css/shareDiv.css
  openkitchen/src/main/webapp/resources/css/spaceD.css
  openkitchen/src/main/webapp/resources/css/teacherD.css
  openkitchen/src/main/webapp/resources/js/scrollMoving.js
  openkitchen/src/main/webapp/resources/js/teacherD.js
Labels: 뷰, 비즈니스로직, 페이지

#210 기능: CTS-HeaderFooter
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/space/user/spaceD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/teacher/user/teacherD.jsp
  openkitchen/src/main/webapp/resources/js/scrollMoving.js
Labels: 뷰, 비즈니스로직, 페이지

#211 기능: teacherDiscription css와 js 설정
  openkitchen/src/main/webapp/WEB-INF/views/admin/perTeacherD2.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherDiscription.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
  openkitchen/src/main/webapp/resources/css/lay03_sideBar.css
  openkitchen/src/main/webapp/resources/css/makeContents.css
  openkitchen/src/main/webapp/resources/js/teacherDiscription.js
Labels: 뷰, 비즈니스로직, 페이지

#212 기타: 버전 맞추기
  openkitchen/pom.xml
  openkitchen/src/main/java/kr/co/openkitchen/dao/OracleDAO.java
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
Labels: 뷰, 비즈니스로직, 페이지

#214 기타: maven dependancy 변경
  openkitchen/pom.xml
  openkitchen/src/main/java/kr/co/openkitchen/controller/CommonController.java
Labels: dependencies

#216 기능: 이미지 리사이징 모듈
  모듈/imgresizing.html
Labels: 뷰, 비즈니스로직, 페이지

#224 제목 : searchIn 페이지
  openkitchen/src/main/webapp/WEB-INF/views/searchIn.jsp
  openkitchen/src/main/webapp/resources/css/searchIn.css
Labels: 뷰, 페이지

#225 기능: TeacherDTO
  openkitchen/src/main/java/kr/co/openkitchen/dto/TeacherDTO.java
Labels: 비즈니스로직, 페이지

#227 security 01
  openkitchen/src/main/java/kr/co/openkitchen/controller/CommonController.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/webapp/WEB-INF/spring/appServlet/security-context.xml
  openkitchen/src/main/webapp/WEB-INF/views/admin/adminIndex.jsp
  openkitchen/src/main/webapp/WEB-INF/views/header.jsp
  openkitchen/src/main/webapp/WEB-INF/views/login/login.jsp
  openkitchen/src/main/webapp/WEB-INF/views/login/signUp.jsp
Labels: 뷰, 비즈니스로직, 페이지

#228 경로조정 및 해더 링크 리스트 추가
  openkitchen/src/main/java/kr/co/openkitchen/controller/AdminController.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/MainController.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/webapp/WEB-INF/views/admin/adminIndex.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/mainAdmin.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/memberAdmin.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perAdmin.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perClassD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perSpaceD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perSpaceD2.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perTeacherD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/admin/perTeacherD2.jsp
  openkitchen/src/main/webapp/WEB-INF/views/header.jsp
  openkitchen/src/main/webapp/resources/css/Header.css
  openkitchen/src/main/webapp/resources/css/mypageIn.css
Labels: 페이지

#230 기능 : 클래스 디테일 페이지 구현
  openkitchen/src/main/java/kr/co/openkitchen/controller/ClassController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/Dao.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/OracleDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/DetailCScheDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/DetailClassDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/ServiceImple.java
  openkitchen/src/main/java/kr/co/openkitchen/service/ServiceInter.java
  openkitchen/src/main/webapp/WEB-INF/Mapper.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
Labels: 뷰, 비즈니스로직, 페이지

#243 자주하는질문 연결및 이미지 이름 리페어
  openkitchen/src/main/java/kr/co/openkitchen/controller/MainController.java
  openkitchen/src/main/webapp/WEB-INF/views/header.jsp
  openkitchen/src/main/webapp/resources/img/spaceimg/s16-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s17-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s18-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/spaceimg/s20-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t16-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t16-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t17-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t17-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t18-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t18-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t19-ds-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t19-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t20-ds-01jpg
  openkitchen/src/main/webapp/resources/img/teacherimg/t20-ms-01.jpg
Labels: 환경설정

#244 기능: 선생님 등록 백엔드 및 프론트단 비즈니스 로직
  openkitchen/.settings/org.eclipse.wst.common.component
  openkitchen/pom.xml
  openkitchen/src/main/java/kr/co/openkitchen/controller/TeacherController.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/TeacherRegistDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistTeacherImple.java
  openkitchen/src/main/webapp/WEB-INF/spring/appServlet/spring-ctx.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherDiscription.jsp
  openkitchen/src/main/webapp/resources/css/teacherBase.css
  openkitchen/src/main/webapp/resources/js/teacherBase.js
Labels: 비즈니스로직, 페이지

#245 기능: CSRF 토큰
  openkitchen/src/main/java/kr/co/openkitchen/controller/TeacherController.java
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/resources/js/teacherBase.js
Labels: 비즈니스로직, 페이지

#247 기능: 선생님 등록 페이지
  openkitchen/src/main/java/kr/co/openkitchen/controller/TeacherController.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistTeacherImple.java
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/resources/js/teacherBase.js
Labels: 비즈니스로직, 페이지

#248 기타: 주석 추가
  openkitchen/src/main/java/kr/co/openkitchen/controller/TeacherController.java
Labels: 뷰

#261 기능: 선생님 등록 페이지 공간등록 프론트단 로직
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInter.java
  openkitchen/src/main/webapp/WEB-INF/views/header.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherDiscription.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
  openkitchen/src/main/webapp/resources/css/classD.css
  openkitchen/src/main/webapp/resources/css/makeContents.css
  openkitchen/src/main/webapp/resources/css/teacherBase.css
  openkitchen/src/main/webapp/resources/css/teacherSpace.css
  openkitchen/src/main/webapp/resources/img/classimg/c21-ms-01.jpg
  openkitchen/src/main/webapp/resources/img/icon/ico-file_add.png
  openkitchen/src/main/webapp/resources/img/icon/ico-people-num.png
  openkitchen/src/main/webapp/resources/js/teacherSpace.js
Labels: 뷰, 비즈니스로직, 페이지

#266 기능: techerspace div 늘리기 기능
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
  openkitchen/src/main/webapp/resources/css/teacherSpace.css
  openkitchen/src/main/webapp/resources/js/teacherSpace.js
Labels: 뷰, 비즈니스로직, 페이지

#272 기능 : 메인 인덱스 페이지 기획전 콘텐츠 이미지 변경
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle1.jpg
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle2.jpg
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle3.jpg
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle4.jpg
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle5.jpg
  openkitchen/src/main/webapp/resources/img/mainbanner/subtitle6.jpg
Labels: 뷰, 페이지

#273 기능 : 메인 인덱스 페이지 인기 클래스 컨텐츠 구현 완료
  openkitchen/src/main/java/kr/co/openkitchen/controller/MainController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MDaoInter.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MainDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/BestClassDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/CserviceInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MainService.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MserviceInter.java
  openkitchen/src/main/webapp/WEB-INF/mapper/classMapper.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
Labels: 뷰, 비즈니스로직, 페이지

#275 버그:teacherSpace 이름 변경
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
Labels: 뷰, 비즈니스로직, 페이지

#277 기능 : 슬라이드 자동 progressBar 기능 추가(메인, 클래스)
  openkitchen/src/main/webapp/WEB-INF/views/class/user/classD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/resources/css/class-slick.css
  openkitchen/src/main/webapp/resources/css/main-slick.css
  openkitchen/src/main/webapp/resources/css/slick-theme.css
  openkitchen/src/main/webapp/resources/css/slick.css
  openkitchen/src/main/webapp/resources/js/main-slick.js
  openkitchen/src/main/webapp/resources/js/slick.js
Labels: 뷰, 비즈니스로직, 페이지

#281 Feature/teacher base db
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/RegisterDaoInter.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/TeacherRegistDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/TeacherRegistDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/TeacherRegistDtoS.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistTeacherImple.java
  openkitchen/src/main/webapp/WEB-INF/mapper/teacherRegistMapper.xml
  openkitchen/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/index.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherBase.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/teacher/teacherSpace.jsp
  openkitchen/src/main/webapp/resources/js/teacherBase.js
  openkitchen/src/main/webapp/resources/js/teacherDiscription.js
Labels: 비즈니스로직, 페이지

#307 기능: cookbookpage
  openkitchen/src/main/java/kr/co/openkitchen/classes/GenericOne.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/Util.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/CommonController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageCookBookDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageCookDaoInter.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageDaoInter.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/CookBookDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/MypageDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookBook.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageServiceImple.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageServiceInter.java
  openkitchen/src/main/webapp/WEB-INF/mapper/mypageCookMapper.xml
  openkitchen/src/main/webapp/WEB-INF/mapper/mypageMapper.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookBookD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookIn.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/mypageIn.jsp
  openkitchen/src/main/webapp/resources/css/Header.css
  openkitchen/src/main/webapp/resources/css/contents_board.css
  openkitchen/src/main/webapp/resources/js/cookBookD.js
  openkitchen/src/main/webapp/resources/js/cookIn.js
Labels: 비즈니스로직, 페이지

#312 기능: 예약 클래스 페이지 백엔드,프론트단 로직
  openkitchen/src/main/java/kr/co/openkitchen/classes/GenericOne.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/Util.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/CookBookDTO.java
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookBookD.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookIn.jsp
  openkitchen/src/main/webapp/resources/css/contents_board.css
  openkitchen/src/main/webapp/resources/js/cookBookD.js
Labels: 비즈니스로직, 페이지

#314 기능: 마이페이지 예약 종료 클래스 프론트,백엔드 로직
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageCookEndDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookEnd.java
  openkitchen/src/main/webapp/WEB-INF/mapper/mypageCookMapper.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookEndD.jsp
  openkitchen/src/main/webapp/resources/js/cookEndD.js
Labels: 뷰, 비즈니스로직, 페이지

#316 기능: 마이페지 예약 취소/환불 페이지 프론트,백엔드
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageCookRefundDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/CookRefundDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookRefund.java
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/cookRefundD.jsp
  openkitchen/src/main/webapp/resources/js/cookRefundD.js
Labels: 비즈니스로직, 페이지

#317 기능: classSpace 페이지 ajax 로딩 기능
  openkitchen/src/main/webapp/WEB-INF/mapper/classRegistMapper.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/applyClass.jsp
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/classSpace.jsp
  openkitchen/src/main/webapp/resources/css/makeContentsC.css
  openkitchen/src/main/webapp/resources/js/classSpace.js
Labels: 비즈니스로직, 페이지

#326 기능: ongoingClass 백엔드,프론트단 로직
  openkitchen/src/main/java/kr/co/openkitchen/classes/GenericOne.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/Util.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageOngoingClassDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/OngoingClassDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageOngoingClass.java
  openkitchen/src/main/webapp/WEB-INF/mapper/mypageOpenClassMapper.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/ongoingClass.jsp
  openkitchen/src/main/webapp/resources/js/ongoingClass.js
Labels: 뷰, 비즈니스로직, 페이지

#329 기능:CompleteClass 페이지 백엔드,프론트단 로직
  openkitchen/src/main/java/kr/co/openkitchen/classes/GenericOne.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/Util.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/dao/MypageCompleteClassDAO.java
  openkitchen/src/main/java/kr/co/openkitchen/dto/CompleteClassDTO.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCompleteClass.java
  openkitchen/src/main/webapp/WEB-INF/mapper/mypageOpenClassMapper.xml
  openkitchen/src/main/webapp/WEB-INF/sqlMapConfig.xml
  openkitchen/src/main/webapp/WEB-INF/views/mypage/class/completeClass.jsp
  openkitchen/src/main/webapp/resources/css/contents_board.css
  openkitchen/src/main/webapp/resources/js/completeClass.js
Labels: 뷰, 비즈니스로직, 페이지

#330 Feature/factory pattern
  openkitchen/src/main/java/kr/co/openkitchen/classes/MypageCookFactory.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/MypageCookInterType.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/MypageOpenCFactory.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/MypageOpenCType.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/RegistServiceFactory.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/RegistServiceFactoryF.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/RegistServiceType.java
  openkitchen/src/main/java/kr/co/openkitchen/classes/RegistServiceTypeF.java
  openkitchen/src/main/java/kr/co/openkitchen/controller/UserController.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCompleteClass.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookBook.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookEnd.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookOrder.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageCookRefund.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageOngoingClass.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageOpenClassInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageOpenClassOrder.java
  openkitchen/src/main/java/kr/co/openkitchen/service/MypageStandByClass.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistClassImple.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistClassImpleS.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistClassImpleSch.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistOrderService.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistOrderServiceF.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInter.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistServiceInterF.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistTeacherImple.java
  openkitchen/src/main/java/kr/co/openkitchen/service/RegistTeacherImpleS.java
Labels: 비즈니스로직, 페이지
